# Generated by Django 3.2.7 on 2021-09-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_company_product_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='categorys',
            field=models.ManyToManyField(blank=True, related_name='samples', to='main.Category'),
        ),
    ]
